# -*- coding: utf-8 -*-
"""FR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3c-IxW6y6weRCtomp3uG9jqz-dRrkqy
"""

def install(package):
    subprocess.check_call([sys.executable, "-m", "!pip", "install", package])

def face_recog(image_file):
  import sys
  import subprocess
  import matplotlib.pyplot as plt
  try:
    import face_recognition
  except ModuleNotFoundError:
    install(face_recognition)
  import face_recognition  
  import PIL.Image
  import PIL.ImageDraw

  # Load the jpg file into a numpy array
  #print(args.image_file)
  image = face_recognition.load_image_file(image_file)

  # Find all the faces in the image
  face_locations = face_recognition.face_locations(image)

  number_of_faces = len(face_locations)
  print("I found {} face(s) in this photograph.".format(number_of_faces))

  pil_image = PIL.Image.fromarray(image)

  face_encodings = face_recognition.face_encodings(image, known_face_locations=face_locations)
  print("Length of each face_encodings ",len(face_encodings[0]))
  print()

  for i,face_location in enumerate(face_locations):
    # Print the location of each face in this image. Each face is a list of co-ordinates in (top, right, bottom, left) order.
    top, right, bottom, left = face_location
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))
    print("It's corresponding encoding", face_encodings[i][0:5] , "...")
    print()
    # Let's draw a box around the face
    draw = PIL.ImageDraw.Draw(pil_image)
    draw.rectangle([left, top, right, bottom], outline="yellow", width=5)
  
  # Display the image on screen
  output_file = str(image_file.split('/')[-1].split('.')[0] + ".jpg")
  pil_image.save(output_file)
  pil_image
  return pil_image, face_encodings

# output_image, encodings = face_recog(image_file = "/content/drive/My Drive/Colab Notebooks/Face Recognition/2a04bfda-5f6e-4140-adaf-1a7323b5080a.JPG")

output_image, encodings = face_recog(image_file = "PATH OF YOUR IMAGE FILE GOES HERE")
with open("encodings.txt", "w") as output:
    output.write(str(encodings))
output_image

